table! {
    wp_posts (ID) {
        ID -> Unsigned<Integer>,
        post_author -> Unsigned<Integer>,
        post_date -> Datetime,
        //post_date_gmt -> Nullable<Datetime>,
        post_content -> Text,
        post_title -> Text,
        post_excerpt -> Text,
        post_status -> VarChar,
        comment_status -> VarChar,
        ping_status -> VarChar,
        post_password -> VarChar,
        post_name -> VarChar,
        to_ping -> Text,
        pinged -> Text,
        post_modified -> Datetime,
        //post_modified_gmt -> Nullable<Datetime>,
        post_content_filtered -> VarChar,
        post_parent -> Unsigned<Integer>,
        guid -> VarChar,
        menu_order -> Integer,
        post_type -> VarChar,
        post_mime_type -> VarChar,
        comment_count -> Integer,
    }
}
